const { persons, vehicles } = require('./ui-fixture');
// Synthetic operational records, never copied from the operator database.
const fleet = vehicles.map((v, i) => ({ ...v, person_name: 'Demo Berger ' + (i + 1), category_name: 'Wohnmobil',
  accrued_cost: 680, accrued: 680, length_m: 6, width_m: 2.4, height_m: 2.7, weight_t: 3,
  end_date: i < 3 ? '2026-09-' + (10 + i) : null, reserved_from: i === 0 ? '2026-09-04' : null,
}));
const invoice = { id: 1, person_id: 1, number: '2026-0012', status: 'offen', issued_on: '2026-09-01', due_on: '2026-09-15',
  person_name: 'Demo Berger 1', total: 680, subtotal: 680, tax_amount: 0, paid_amount: 0, open_amount: 680, kleinunternehmer: true,
  seller: { name: 'Demo Einstellbetrieb', address: 'Musterstraße 12\n0000 Musterort' }, buyer: { name: 'Demo Berger 1', address: 'Beispielweg 4\n0000 Musterort' },
  items: [{ pos: 1, description: 'Einstellplatz Wohnmobil · Januar bis August', quantity: 8, unit_amount: 85, line_total: 680 }],
};
const charges = [
  { id: 1, person_id: 1, person_name: 'Demo Berger 1', description: 'Innenreinigung', amount: 45, quantity: 1, total: 45, charged_on: '2026-09-02', paid: false },
  { id: 2, person_id: 2, person_name: 'Demo Gruber 2', description: 'Stromanschluss', amount: 20, quantity: 2, total: 40, charged_on: '2026-09-01', paid: true },
  { id: 3, person_id: 1, person_name: 'Demo Berger 1', vehicle_id: 1, vehicle_label: 'Demo Wohnmobil 1', description: 'Batterieservice', amount: 30, quantity: 1, total: 30, charged_on: '2026-08-30', paid: false },
];
const hall = { id: 1, garage_id: 1, name: 'Halle Nord', spot_count: 1, geometry: { Wm: 14, Hm: 9, shape: 'rect', tor: 3, load: 5,
  floor: [[0, 0], [14, 0], [14, 9], [0, 9]], excl: [] } };
const overrides = {
  '/categories': [{ id: 1, name: 'Wohnmobil', default_monthly_cost: 85, default_yearly_cost: 1020 }],
  '/persons': persons, '/vehicles': fleet, '/vehicles/unassigned': fleet.slice(1), '/charges': charges,
  '/services': [{ id: 1, name: 'Innenreinigung', default_amount: 45 }, { id: 2, name: 'Stromanschluss', default_amount: 20 }],
  '/users': [{ id: 1, username: 'Demo Admin', role: 'admin', email: 'admin@example.invalid', totp_enabled: true },
    { id: 2, username: 'Demo Team', role: 'editor', email: 'team@example.invalid', totp_enabled: false },
    { id: 3, username: 'Demo Lesekonto', role: 'reader', email: 'lesen@example.invalid', totp_enabled: true }],
  '/persons/1/stats': { person_name: 'Demo Berger 1', year: 2026, balance: 755, total_accrued: 680, total_charges: 75, total_paid: 0,
    payments_year: 0, payments_total: 0, agreements: [], recurring_charges: [], years: [{ year: 2025, cost: 600 }, { year: 2026, cost: 755 }],
    monthly_accrued: [85, 85, 85, 85, 85, 85, 85, 85, 75, 0, 0, 0] },
  '/persons/1/payments': [], '/persons/1/invoices': [invoice], '/persons/1/recurring': [], '/persons/1/attachments': [],
  '/persons/1/timeline': [{ kind: 'charge', text: 'Innenreinigung erfasst', at: '2026-09-02T10:00:00Z' }],
  '/vehicles/1/photos': [], '/vehicles/1/history': [], '/vehicles/1/handovers': [], '/vehicles/1/attachments': [],
  '/invoices/1': invoice,
  '/invoices/overdue': [{ ...invoice, days_overdue: 0, open_amount: 680 }],
  '/reports/tax-year': { year: 2025, total_by_date: 48310, total_with_rule: 48190, count: 412, reversed_count: 3, reversed_amount: 240,
    slider_count: 7, slider_amount: 595, by_month: [4120, 3860, 3940, 4010, 3980, 4050, 4180, 3920, 4060, 4110, 3990, 4090],
    by_kind: [{ key: 'vehicle', label: 'Einstellplatz-Miete', amount: 34300 }, { key: 'agreement', label: 'Pauschalen', amount: 8213 },
      { key: 'recurring', label: 'Nebenkosten', amount: 3382 }, { key: 'charge', label: 'Zusatzkosten', amount: 2415 }],
    by_method: [{ key: 'ueberweisung', label: 'Überweisung', amount: 39110 }, { key: 'bar', label: 'Bar', amount: 9200 }],
    shifted_in: [{ id: 9, paid_on: '2026-01-08', person: 'Demo Berger 1', amount: 85, period: '2025-12', rule_year: 2025 }],
    shifted_out: [{ id: 10, paid_on: '2025-12-22', person: 'Demo Gruber 2', amount: 205, period: '2026-01', rule_year: 2026 }],
    review_payments: [{ id: 11, paid_on: '2025-11-04T00:00:00Z', booked_on: '2025-11-04T00:00:00Z', person: 'Demo Müller 3', amount: 85, property_id: 1 }],
    properties: [{ id: 1, name: 'Standort Nord', address: 'Musterstraße 12', garages: 'Halle Nord', garage_ids: [1], is_default: true },
      { id: 2, name: 'Standort Süd', address: 'Nebenweg 4', garages: 'Halle Süd', garage_ids: [2], is_default: false }],
    property_summaries: [{ id: 1, name: 'Standort Nord', address: 'Musterstraße 12', income_by_date: 40310, income_with_rule: 40190, expenses: 8120, depreciation: 1800, surplus: 30390, surplus_with_rule: 30270 },
      { id: 2, name: 'Standort Süd', address: 'Nebenweg 4', income_by_date: 8000, income_with_rule: 8000, expenses: 1600, depreciation: 500, surplus: 5900, surplus_with_rule: 5900 }],
    categories: [{ id: 1, key: 'maintenance', label: 'Erhaltung / Instandsetzung', e1b_code: '9520', sort_order: 10 },
      { id: 2, key: 'insurance', label: 'Versicherungen', e1b_code: '9530', sort_order: 40 }],
    expenses: [{ id: 1, property_id: 1, property: 'Standort Nord', category_id: 1, category: 'Erhaltung / Instandsetzung', e1b_code: '9520', paid_on: '2025-08-14', amount: 620, vat_amount: 103.33, payee: 'Torservice GmbH', description: 'Wartung Hallentor', payment_method: 'ueberweisung', reversed: false, receipt_count: 1 }],
    recurring_expenses: [{ id: 1, property_id: 1, property: 'Standort Nord', category_id: 2, category: 'Versicherungen', description: 'Gebäudeversicherung', amount: 120, payment_method: 'ueberweisung', frequency: 'monthly', due_day: 1, due_month: 1, start_on: '2025-01-01', active: true }],
    assets: [{ id: 1, property_id: 1, property: 'Standort Nord', name: 'Torantrieb', in_service_on: '2025-07-01', depreciable_basis: 3600, useful_life_years: 10, half_year_rule: true, notes: '', year_depreciation: 180 }],
    e1b: [{ property_id: 1, code: '9460', label: 'Einnahmen', amount: 40310 }, { property_id: 1, code: '9500', label: 'AfA', amount: 1800 },
      { property_id: 1, code: '9520', label: 'Erhaltung / Instandsetzung', amount: 620 }, { property_id: 1, code: '9530', label: 'Übrige Werbungskosten', amount: 7500 },
      { property_id: 2, code: '9460', label: 'Einnahmen', amount: 8000 }, { property_id: 2, code: '9500', label: 'AfA', amount: 500 }],
    settings: { small_business_limit: 55000, warning_percent: 90, vat_opted_in: false }, expense_total: 9720,
    depreciation_total: 2300, surplus: 36290, surplus_with_rule: 36170, small_business_percent: 87.84,
    small_business_exceeded: false, locked: false },
  '/billing/settings': { seller_name: 'Demo Einstellbetrieb', seller_address: 'Musterstraße 12', kleinunternehmer: true,
    invoice_prefix: '2026-', next_invoice_no: 13, number_pad: 4, payment_terms_days: 14 },
  '/auth/sessions': [{ token: 'fixture-current', user_agent: 'Chrome', ip: '192.0.2.1', current: true, last_seen: '2026-09-10T09:00:00Z' },
    { token: 'fixture-other', user_agent: 'Firefox', ip: '192.0.2.2', current: false, last_seen: '2026-09-09T17:00:00Z' }],
  '/backup/status': { enabled: true, scheduled: true, s3: false, dir: '/backups', schema_version: 'demo', settings: {},
    status: { last_volume_at: '2026-09-10T03:00:00Z', last_volume_ok: true, last_volume_size: 2048000, restore_tested_at: '2026-09-10T03:01:00Z' },
    files: [{ name: 'parkrr-demo-20260910.dump.enc', modified: '2026-09-10T03:00:00Z', size: 2048000 }], s3_files: [] },
  '/audit': [{ id: 1, created_at: '2026-09-10T09:00:00Z', username: 'Demo Admin', action: 'create', entity: 'person', entity_id: 1, description: 'Demo Berger 1 angelegt', details: {} }],
  '/garages': [{ id: 1, name: 'Standort Nord', hall_count: 2 }, { id: 2, name: 'Standort Süd', hall_count: 0 }],
  '/garages/1/halls': [hall, { ...hall, id: 2, name: 'Halle Süd', spot_count: 0 }],
  '/halls/1/plan': { hall, garage_name: 'Standort Nord', spots: [{ id: 1, vehicle_id: 1, vehicle_label: 'Demo Wohnmobil 1', vehicle_type: 'Wohnmobil',
    person_id: 1, person_name: 'Demo Berger 1', length_m: 6, width_m: 2.4, height_m: 2.7, geometry: { x: 1, y: 1, w: 6, h: 2.4 } }] },
  '/planner-icons': [],
  '/portal/summary': { person_name: 'Demo Berger 1', open_total: 680, vehicles: [{ label: 'Demo Wohnmobil 1', status: 'stored' }],
    invoices: [{ ...invoice, open: 680 }], handovers: [] },
};
module.exports = { overrides, invoice, charges, hall };
